(source gnu)
(depends-on "queue")

(source melpa)
(depends-on "cider")
(depends-on "magit")
(depends-on "find-file-in-project")
(depends-on "smex")
(depends-on "ido-ubiquitous")
(depends-on "company")
(depends-on "flymake-python-pyflakes")
(depends-on "auto-complete")
(depends-on "better-defaults")
(depends-on "rainbow-delimiters")
(depends-on "paredit")
(depends-on "smartparens")
(depends-on "ag")
(depends-on "clojure-mode")
(depends-on "gist")
(depends-on "projectile")
(depends-on "markdown-mode")
(depends-on "htmlize")
(depends-on "puppet-mode")
(depends-on "haskell-mode")
(depends-on "graphviz-dot-mode")
(depends-on "yaml-mode")
(depends-on "web-mode")
(depends-on "json-mode")
(depends-on "org-trello")

;; For hublo
(depends-on "ht")
(depends-on "dash")
(depends-on "mustache")
;; End hublo specific deps

;;(depends-on "o-blog" :git "https://github.com/renard/o-blog"
;;                     :branch "o-blog-v1"
;;                     :files ("*" (:exclude ".git")))
(depends-on "go-mode")
(depends-on "rust-mode")
(depends-on "slime")
(depends-on "restclient")
(depends-on "color-theme-solarized")

(source org)
(depends-on "org")
(depends-on "org-plus-contrib")
