(menu-bar-mode t)
(global-font-lock-mode t)
(column-number-mode t)
(show-paren-mode t)
(setq inhibit-splash-screen t)
(blink-cursor-mode t)
(set-fringe-style -1)
(scroll-bar-mode -1)
(tool-bar-mode -1)
(tooltip-mode -1)
(delete-selection-mode t)
(fset 'yes-or-no-p 'y-or-n-p)
(setq make-backup-files nil)
(setq auto-save-default nil)
